//! OpenCode integration: a `tool.execute.*` plugin.
//!
//! OpenCode auto-loads any plugin file under `.opencode/plugins/` (project) or
//! `~/.config/opencode/plugins/` (global). Our plugin prepends a reminder to
//! `bash` search commands (`tool.execute.before`) and appends one after the
//! `grep`/`glob`/`read` tools (`tool.execute.after`), gated on an indexed repo.
//! Every hook is wrapped in try/catch so it can never break a tool call.

use anyhow::Result;

use super::{display_path, write_file_if_changed, Scope};

const PLUGIN_JS: &str = r#"// codesearch OpenCode plugin (generated by `codesearch install opencode`)
// Nudges the agent toward `codesearch search/context/impact` instead of grepping
// or reading source files one by one — but only when this repo is indexed.
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";

const SEARCH_RE = /(^|[^\w-])(grep|rg|ripgrep|ag|ack|find|fd)([^\w-]|$)/;
const SOURCE_RE = /\.(rs|py|js|jsx|ts|tsx|mjs|go|java|rb|c|h|cpp|hpp|cc|cs|kt|swift|php|scala|lua|sh|md|mdx|rst|txt)$/i;

const SEARCH_NUDGE =
  "[codesearch] This repo is indexed. Prefer `codesearch search \"<question>\"` (semantic + keyword hybrid) over grepping raw files; use grep only for exact-string matches.";
const READ_NUDGE =
  "[codesearch] This repo is indexed. Prefer `codesearch search`, `codesearch context <symbol>`, or `codesearch impact <symbol>` over reading files one by one to understand code.";

function indexed(dir) {
  let cur = dir;
  for (let i = 0; i < 40 && cur; i++) {
    if (existsSync(join(cur, ".codesearch", "project.json"))) return true;
    const parent = dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  return false;
}

export const CodesearchPlugin = async ({ directory }) => {
  return {
    "tool.execute.before": async (input, output) => {
      try {
        if (input.tool !== "bash" || !indexed(directory)) return;
        const cmd = output?.args?.command;
        if (typeof cmd !== "string" || cmd.includes("codesearch")) return;
        if (!SEARCH_RE.test(cmd)) return;
        output.args.command = `echo ${JSON.stringify(SEARCH_NUDGE)}; ` + cmd;
      } catch (_) {
        /* never break the tool */
      }
    },
    "tool.execute.after": async (input, output) => {
      try {
        if (!indexed(directory)) return;
        let note = null;
        if (input.tool === "grep" || input.tool === "glob") {
          note = SEARCH_NUDGE;
        } else if (input.tool === "read") {
          const p = output?.args?.filePath || output?.args?.path || "";
          if (SOURCE_RE.test(p)) note = READ_NUDGE;
        }
        if (note && typeof output?.output === "string") {
          output.output += `\n\n${note}`;
        }
      } catch (_) {
        /* never break the tool */
      }
    },
  };
};
"#;

fn plugin_path(scope: Scope) -> Result<std::path::PathBuf> {
    let base = match scope {
        Scope::Global => super::home_dir()?.join(".config").join("opencode"),
        Scope::Project => std::env::current_dir()?.join(".opencode"),
    };
    Ok(base.join("plugins").join("codesearch.js"))
}

pub fn install(scope: Scope) -> Result<Vec<String>> {
    let path = plugin_path(scope)?;
    let changed = write_file_if_changed(&path, PLUGIN_JS)?;
    Ok(vec![format!(
        "{} {} (tool.execute.before/after plugin)",
        if changed { "wrote" } else { "unchanged" },
        display_path(&path)
    )])
}

pub fn uninstall(scope: Scope) -> Result<Vec<String>> {
    let path = plugin_path(scope)?;
    if path.exists() {
        std::fs::remove_file(&path)?;
        Ok(vec![format!("removed {}", display_path(&path))])
    } else {
        Ok(vec![format!(
            "no plugin at {} (nothing to remove)",
            display_path(&path)
        )])
    }
}
