//! Pi integration: a live TypeScript extension.
//!
//! Pi auto-discovers extensions under `~/.pi/agent/extensions/*.ts` (global) or
//! `.pi/extensions/*.ts` (project). We subscribe to `tool_call` (to catch the
//! agent reaching for a search) and `tool_result` (to append the nudge to what
//! the model sees afterwards), gated on an indexed repo. Mutating `tool_result`
//! content is non-destructive — it only adds a reminder, never blocks a tool.

use anyhow::Result;

use super::{display_path, write_file_if_changed, Scope};

const EXTENSION_TS: &str = r#"// codesearch Pi extension (generated by `codesearch install pi`)
// Nudges the agent toward `codesearch search/context/impact` instead of grepping
// or reading source files one by one — but only when this repo is indexed.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";

const SEARCH_RE = /(^|[^\w-])(grep|rg|ripgrep|ag|ack|find|fd)([^\w-]|$)/;
const SOURCE_RE = /\.(rs|py|js|jsx|ts|tsx|mjs|go|java|rb|c|h|cpp|hpp|cc|cs|kt|swift|php|scala|lua|sh|md|mdx|rst|txt)$/i;

const SEARCH_NUDGE =
  "[codesearch] This repo is indexed. Prefer `codesearch search \"<question>\"` (semantic + keyword hybrid) over grepping raw files; use grep only for exact-string matches.";
const READ_NUDGE =
  "[codesearch] This repo is indexed. Prefer `codesearch search`, `codesearch context <symbol>`, or `codesearch impact <symbol>` over reading files one by one to understand code.";

function indexed(dir: string): boolean {
  let cur = dir;
  for (let i = 0; i < 40 && cur; i++) {
    if (existsSync(join(cur, ".codesearch", "project.json"))) return true;
    const parent = dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  return false;
}

// Decide which nudge (if any) a given tool invocation warrants.
function nudgeFor(toolName: string, input: any): string | null {
  if (toolName === "bash") {
    const cmd = input?.command;
    if (typeof cmd !== "string" || cmd.includes("codesearch")) return null;
    return SEARCH_RE.test(cmd) ? SEARCH_NUDGE : null;
  }
  if (toolName === "grep" || toolName === "find") return SEARCH_NUDGE;
  if (toolName === "read") {
    const p = input?.path ?? input?.file_path ?? "";
    return SOURCE_RE.test(p) ? READ_NUDGE : null;
  }
  return null;
}

export default function (pi: ExtensionAPI) {
  pi.on("tool_result", async (event, ctx) => {
    try {
      if (!indexed(ctx.cwd)) return;
      const note = nudgeFor(event.toolName, event.input);
      if (!note) return;
      const content = Array.isArray(event.content) ? event.content.slice() : [];
      content.push({ type: "text", text: note });
      return { content };
    } catch (_) {
      /* never break the tool */
    }
  });
}
"#;

fn extension_path(scope: Scope) -> Result<std::path::PathBuf> {
    let base = match scope {
        Scope::Global => super::home_dir()?
            .join(".pi")
            .join("agent")
            .join("extensions"),
        Scope::Project => std::env::current_dir()?.join(".pi").join("extensions"),
    };
    Ok(base.join("codesearch.ts"))
}

pub fn install(scope: Scope) -> Result<Vec<String>> {
    let path = extension_path(scope)?;
    let changed = write_file_if_changed(&path, EXTENSION_TS)?;
    Ok(vec![format!(
        "{} {} (tool_result extension)",
        if changed { "wrote" } else { "unchanged" },
        display_path(&path)
    )])
}

pub fn uninstall(scope: Scope) -> Result<Vec<String>> {
    let path = extension_path(scope)?;
    if path.exists() {
        std::fs::remove_file(&path)?;
        Ok(vec![format!("removed {}", display_path(&path))])
    } else {
        Ok(vec![format!(
            "no extension at {} (nothing to remove)",
            display_path(&path)
        )])
    }
}
